spring:
  application:
    name: valuation-consumer-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: valuation-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "afsdigital.grahamselect.*"
        spring.json.key.default.type: "afsdigital.grahamselect.common.domain.entities.FinancialDataKey"
        spring.json.value.default.type: "afsdigital.grahamselect.common.domain.entities.FinancialDataEvent"
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false