// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/upload/presentation/providers/upload_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:frontend/src/features/upload/domain/entities/app_file.dart'
    as _i6;
import 'package:frontend/src/features/upload/domain/entities/upload_processing_status.dart'
    as _i3;
import 'package:frontend/src/features/upload/domain/entities/upload_result.dart'
    as _i2;
import 'package:frontend/src/features/upload/domain/repositories/upload_repository.dart'
    as _i4;
import 'package:frontend/src/features/upload/domain/usecases/upload_b3_file_usecase.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUploadResult_0 extends _i1.SmartFake implements _i2.UploadResult {
  _FakeUploadResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadProcessingStatus_1 extends _i1.SmartFake
    implements _i3.UploadProcessingStatus {
  _FakeUploadProcessingStatus_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadRepository_2 extends _i1.SmartFake
    implements _i4.UploadRepository {
  _FakeUploadRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UploadRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadRepository extends _i1.Mock implements _i4.UploadRepository {
  MockUploadRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UploadResult> uploadFile(_i6.AppFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [file]),
            returnValue: _i5.Future<_i2.UploadResult>.value(
              _FakeUploadResult_0(this, Invocation.method(#uploadFile, [file])),
            ),
          )
          as _i5.Future<_i2.UploadResult>);

  @override
  _i5.Future<_i2.UploadResult> uploadB3File(_i6.AppFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#uploadB3File, [file]),
            returnValue: _i5.Future<_i2.UploadResult>.value(
              _FakeUploadResult_0(
                this,
                Invocation.method(#uploadB3File, [file]),
              ),
            ),
          )
          as _i5.Future<_i2.UploadResult>);

  @override
  _i5.Future<_i3.UploadProcessingStatus> fetchB3UploadStatus(
    String? correlationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchB3UploadStatus, [correlationId]),
            returnValue: _i5.Future<_i3.UploadProcessingStatus>.value(
              _FakeUploadProcessingStatus_1(
                this,
                Invocation.method(#fetchB3UploadStatus, [correlationId]),
              ),
            ),
          )
          as _i5.Future<_i3.UploadProcessingStatus>);
}

/// A class which mocks [UploadB3FileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadB3FileUseCase extends _i1.Mock
    implements _i7.UploadB3FileUseCase {
  MockUploadB3FileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.UploadRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUploadRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.UploadRepository);

  @override
  _i5.Future<_i2.UploadResult> call(_i6.AppFile? file) =>
      (super.noSuchMethod(
            Invocation.method(#call, [file]),
            returnValue: _i5.Future<_i2.UploadResult>.value(
              _FakeUploadResult_0(this, Invocation.method(#call, [file])),
            ),
          )
          as _i5.Future<_i2.UploadResult>);
}
