// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/upload/presentation/pages/upload_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:frontend/src/features/upload/domain/usecases/upload_file_usecase.dart'
    as _i2;
import 'package:frontend/src/features/upload/presentation/providers/upload_provider.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUploadFileUseCase_0 extends _i1.SmartFake
    implements _i2.UploadFileUseCase {
  _FakeUploadFileUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UploadProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadProvider extends _i1.Mock implements _i3.UploadProvider {
  MockUploadProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UploadFileUseCase get uploadFileUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#uploadFileUseCase),
            returnValue: _FakeUploadFileUseCase_0(
              this,
              Invocation.getter(#uploadFileUseCase),
            ),
          )
          as _i2.UploadFileUseCase);

  @override
  _i3.UploadState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i3.UploadState.idle,
          )
          as _i3.UploadState);

  @override
  bool get hasFile =>
      (super.noSuchMethod(Invocation.getter(#hasFile), returnValue: false)
          as bool);

  @override
  bool get canUpload =>
      (super.noSuchMethod(Invocation.getter(#canUpload), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> pickFile() =>
      (super.noSuchMethod(
            Invocation.method(#pickFile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> uploadFile() =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
