// Mocks generated by Mockito 5.4.6 from annotations
// in frontend/test/features/dashboard/presentation/pages/dashboard_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:frontend/src/features/portfolio/domain/entities/custody_position.dart'
    as _i4;
import 'package:frontend/src/features/portfolio/domain/repositories/portfolio_repository.dart'
    as _i2;
import 'package:frontend/src/features/portfolio/presentation/providers/portfolio_provider.dart'
    as _i3;
import 'package:frontend/src/features/profile/presentation/providers/profile_provider.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePortfolioRepository_0 extends _i1.SmartFake
    implements _i2.PortfolioRepository {
  _FakePortfolioRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PortfolioProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockPortfolioProvider extends _i1.Mock implements _i3.PortfolioProvider {
  MockPortfolioProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PortfolioRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePortfolioRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PortfolioRepository);

  @override
  _i3.PortfolioStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i3.PortfolioStatus.initial,
          )
          as _i3.PortfolioStatus);

  @override
  List<_i4.CustodyPosition> get rawCustodyPositions =>
      (super.noSuchMethod(
            Invocation.getter(#rawCustodyPositions),
            returnValue: <_i4.CustodyPosition>[],
          )
          as List<_i4.CustodyPosition>);

  @override
  List<_i4.CustodyPosition> get custodyPositions =>
      (super.noSuchMethod(
            Invocation.getter(#custodyPositions),
            returnValue: <_i4.CustodyPosition>[],
          )
          as List<_i4.CustodyPosition>);

  @override
  _i3.PortfolioStatus get custodyStatus =>
      (super.noSuchMethod(
            Invocation.getter(#custodyStatus),
            returnValue: _i3.PortfolioStatus.initial,
          )
          as _i3.PortfolioStatus);

  @override
  String get sortColumn =>
      (super.noSuchMethod(
            Invocation.getter(#sortColumn),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#sortColumn),
            ),
          )
          as String);

  @override
  bool get sortAscending =>
      (super.noSuchMethod(Invocation.getter(#sortAscending), returnValue: false)
          as bool);

  @override
  _i3.PortfolioStatus get evolutionStatus =>
      (super.noSuchMethod(
            Invocation.getter(#evolutionStatus),
            returnValue: _i3.PortfolioStatus.initial,
          )
          as _i3.PortfolioStatus);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> loadSummary() =>
      (super.noSuchMethod(
            Invocation.method(#loadSummary, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> createManualTrade({
    required String? ticker,
    required String? side,
    required DateTime? tradeDate,
    required double? quantity,
    required double? price,
    required String? broker,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createManualTrade, [], {
              #ticker: ticker,
              #side: side,
              #tradeDate: tradeDate,
              #quantity: quantity,
              #price: price,
              #broker: broker,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void resetStatus() => super.noSuchMethod(
    Invocation.method(#resetStatus, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectAssetClassFilter(String? assetClass) => super.noSuchMethod(
    Invocation.method(#selectAssetClassFilter, [assetClass]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadCustodyPositions() =>
      (super.noSuchMethod(
            Invocation.method(#loadCustodyPositions, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void sortBy(String? column) => super.noSuchMethod(
    Invocation.method(#sortBy, [column]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadEvolutionData() =>
      (super.noSuchMethod(
            Invocation.method(#loadEvolutionData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileProvider extends _i1.Mock implements _i8.ProfileProvider {
  MockProfileProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ProfileState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i8.ProfileState.idle,
          )
          as _i8.ProfileState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> fetchProfile() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateInvestorProfile(String? investorProfile) =>
      (super.noSuchMethod(
            Invocation.method(#updateInvestorProfile, [investorProfile]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
